### ISSUE TITLE
Option to clear database on logout

### ISSUE THREAD

**Issue by james-brattin** [radacovsky/ngrx-store-idb#1]
Hello, I'd like to be able to programmatically delete a database when the user logs out of the application. I had no problem accomplishing this when they close the browser or tab. However, attempting to delete a database without a page refresh does not seem possible. Help?

**Comment by radacovsky** [comment]
Hi @james-brattin . I am not sure what you mean by deleting a database. Do you mean clearing the store?
As for doing something on user log out, there you have to trigger the event yourself because I don't know when does the user log out in your application. Cleaning the store could be accomplished by yourself if you create a redux action that clears the store and that should then be automatically synced (i.e. cleared) into IndexedDb.
Did I answer our question?

**Comment by james-brattin** [comment]
Okay, thank you. Yes, I am trying to clear the store.
